package ipc1.clase8;

import java.awt.Color;
import java.awt.Graphics;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 *
 * @author josed
 */
public class Lienzo extends javax.swing.JPanel implements Runnable {
    private int x;
    Thread hilo;
    boolean primerEjecucion = true;
    boolean direccionDerecha = true;
    AtomicBoolean isPaused = new AtomicBoolean(false);
    
    public Lienzo() {
        initComponents();
        hilo = new Thread(this);
    }

    @Override
    public void paint(Graphics g) {
        g.setColor(Color.gray);
        g.fillRect(0, 0, getWidth(), getHeight());
        
        if (primerEjecucion) {
            x = getWidth()/2 - 15;
            primerEjecucion = false;
        }
        g.setColor(Color.red);
        g.fillOval(x, (getHeight() / 2) - 15, 30, 30);
    }
    
    @Override
    public synchronized void run() {
        try {
            while (true) {
                while (this.isPaused.get()) {
                }
     
                if (direccionDerecha && x >= getWidth() - 30 || !direccionDerecha && x <= 0) {
                    direccionDerecha = !direccionDerecha;
                }
                
                if (direccionDerecha) {
                    x += 10;
                } else {
                    x -= 10;
                }
              
                Thread.sleep(100);
                repaint();
            }
        } catch (InterruptedException e) {
            System.err.println("Sucedio un error " + e);
        }
    }
    
    public void inicio() {
        hilo.start();
    }

    public void pausa() {
        isPaused.set(true);
    }

    public void continuar() {
        isPaused.set(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
